runtime: python39  # Use the appropriate Python runtime version

entrypoint: python3 app.py  # Specify the entry point to start your script

handlers:
- url: /.*
  script: auto
- url: /data
  static_dir: data

instance_class: F1  # Set the instance class to F1 or choose the appropriate class

automatic_scaling:
  target_cpu_utilization: 0.65  # Adjust the CPU utilization threshold as needed
  min_instances: 1
  max_instances: 2  # Set the maximum number of instances based on your requirements


