services:
  app:
    build: .
    image:  docker.io/maximilianpichler/planeswalker_companion:latest
    container_name: nissa_dev
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped