[tool.poetry]
name = "mtg"
version = "0.1.0"
description = ""
authors = ["florian.krempl <florian.krempl@outlook.com>"]
license = "mit"
readme = "README.md"
packages = [{ include = "mtg" }]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.0.3"
ipykernel = "^6.25.1"
pdfminer-six = "^20221105"
openai = "^0.27.10"
thefuzz = "^0.20.0"
gradio = "^3.41.2"
spacy = "^3.6.1"
spaczz = "^0.6.0"
black = "^23.7.0"
tqdm = "^4.66.1"
spacy-lookups-data = "^1.0.5"
hnswlib = "^0.7.0"
langchain = "^0.0.314"
tiktoken = "^0.5.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
